In [13]:
import pandas as pd
import json
import sys
import os
from pathlib import Path

# Project root
PROJECT_ROOT = Path.cwd().parent
# Add project root to Python path
sys.path.insert(0, str(PROJECT_ROOT))

from src.data.financial_data_loader import (FinancialDataLoader)
from src.tools.tool_executor import (
    ToolExecutor
)

In [5]:
user_agent = os.getenv(
    "SEC_USER_AGENT"
)

loader = FinancialDataLoader(
    user_agent
)

In [8]:
financials = loader.load("Apple")

In [9]:
financials.head()

,fiscal_year,revenue,net_income,assets,liabilities,cash,operating_cash_flow
0,2017,229.234,48.351,375.319,241.272,20.289,64.225
1,2018,265.595,59.531,365.725,258.578,25.913,77.434
2,2019,260.174,55.256,338.516,248.028,48.844,69.391
3,2020,274.515,57.411,323.888,258.549,38.016,80.674
4,2021,365.817,94.680,351.002,287.912,34.940,104.038

In [10]:
amazon = loader.load("Amazon")

In [11]:
amazon.head()

   fiscal_year  revenue  net_income  assets   cash  operating_cash_flow
0         2006      NaN         NaN     NaN  1.022                  NaN
1         2007      NaN       0.476     NaN  2.539                1.405
2         2008      NaN       0.645   8.314  2.769                1.697
3         2009      NaN       0.902  13.813  3.444                3.293
4         2010      NaN       1.152  18.797  3.777                3.495

In [12]:
amazon.columns

Index(['fiscal_year', 'revenue', 'net_income', 'assets', 'cash',
       'operating_cash_flow'],
      dtype='str')

### Create the executor

In [14]:
executor = ToolExecutor(financials)

### Execute a tool

In [16]:
result = executor.execute(
    "get_revenue_growth"
)

result

   fiscal_year  revenue  revenue_growth_pct
0         2017  229.234                 NaN
1         2018  265.595           15.861958
2         2019  260.174           -2.041078
3         2020  274.515            5.512080
4         2021  365.817           33.259385
5         2022  394.328            7.793788
6         2023  383.285           -2.800461
7         2024  391.035            2.021994
8         2025  416.161            6.425512

In [19]:
profit = executor.execute(
    "get_profit_margin"
)

profit

   fiscal_year  revenue  net_income  net_profit_margin_pct
0         2017  229.234      48.351              21.092421
1         2018  265.595      59.531              22.414202
2         2019  260.174      55.256              21.238095
3         2020  274.515      57.411              20.913611
4         2021  365.817      94.680              25.881793
5         2022  394.328      99.803              25.309641
6         2023  383.285      96.995              25.306234
7         2024  391.035      93.736              23.971256
8         2025  416.161     112.010              26.915064

In [20]:
summary = executor.execute(
    "get_latest_summary"
)

summary

{'fiscal_year': 2025,
 'revenue_billions': 416.161,
 'net_income_billions': 112.01,
 'assets_billions': 359.241,
 'liabilities_billions': 285.508,
 'cash_billions': 35.934,
 'operating_cash_flow_billions': 111.482,
 'revenue_growth_pct': 6.425511782832727,
 'net_profit_margin_pct': 26.91506412181824,
 'operating_cash_flow_margin_pct': 26.788190147563085,
 'liability_to_asset_pct': 79.47533828265705}

### Test a company

In [24]:
amazon_financials = loader.load(
    "Amazon"
)

In [25]:
amazon_executor = ToolExecutor(
    amazon_financials
)

In [26]:
amazon_executor.execute(
    "get_revenue_growth"
)

    fiscal_year  revenue  revenue_growth_pct
0          2006      NaN                 NaN
1          2007      NaN                 NaN
2          2008      NaN                 NaN
3          2009      NaN                 NaN
4          2010      NaN                 NaN
5          2011      NaN                 NaN
6          2012      NaN                 NaN
7          2013      NaN                 NaN
8          2014      NaN                 NaN
9          2015      NaN                 NaN
10         2016  135.987                 NaN
11         2017  177.866           30.796326
12         2018  232.887           30.933962
13         2019  280.522           20.454126
14         2020  386.064           37.623431
15         2021  469.822           21.695367
16         2022  513.983            9.399517
17         2023  574.785           11.829574
18         2024  637.959           10.990892
19         2025  716.924           12.377755